version: 2

updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"

    labels:
      - "dependencies"
      - "python"

    open-pull-requests-limit: 5

    commit-message:
      prefix: "deps"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      npm-dependencies:
        patterns:
          - "*"
    labels:
      - "dependencies"
      - "npm"
    open-pull-requests-limit: 5
    versioning-strategy: "increase-if-necessary"
    commit-message:
      prefix: "deps"
      
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"

    labels:
      - "dependencies"
      - "docker"

    open-pull-requests-limit: 5

    commit-message:
      prefix: "deps"